export default theme => ({
    root: {
        width: '100%',
        height: '100%',
    },
    containerContainer: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
    },
    progressContainer: {
        display: 'flex',
        height: 20,
        alignSelf: 'stretch',
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        width: '100vw',
    },
    progressBar: {
        flexGrow: 1,
    },
    cardContainer: {
        display: 'flex',
        padding: 15,
        border: '1px ' + theme.palette.borderColour + ' solid',
        borderRadius: 15,
        margin: 15,
        width: 'calc(100vw - 62px)',
        justifyContent: 'center',
        flexDirection: 'column',
        textAlign: 'center',
        position: 'relative',
    },
    voteButton: {
        padding: 5,
        paddingRight: 25,
        paddingLeft: 25,
        background: theme.palette.cardColour,
        boxShadow: '0px 1px 3px 0px rgba(0,0,0,0.2), 0px 1px 1px 0px rgba(0,0,0,0.14), 0px 2px 1px -1px rgba(0,0,0,0.12)',
        alignSelf: 'center',
    },
    containerText: {
        position: 'absolute',
        background: theme.palette.pageBackground,
        top: 0,
        left: 45,
        transform: 'translate(0, -50%)',
        padding: 5,
    },
    centreCards: {
        display: 'flex',
        width: '100%',
        justifyContent: 'center',
    },
    playerCards: {
        display: 'flex',
        width: '100%',
        justifyContent: 'center',
    },
});